version: '3.4'
services:

   app:
     image: docker4data/talkvoter:prod-1.0.1
     build:
       context: ./
       dockerfile: talkvoter/Dockerfile
     command: /app/docker-utils/run-app.sh
     volumes:
       - .:/app/proj/
       - static-volume:/app/htdocs/static/
     environment:
       - DATABASE_URL=postgres://postgres@db/postgres
       - SITE_DIR=/app/
       - SECRET_KEY=super secret key
       - PREDICT_ENDPOINT=http://predict:8000/predict/
     networks:
       - talkvoter_net
     depends_on:
       - db
     stdin_open: true
     tty: true
     healthcheck:
       test: ["CMD", "curl", "localhost", "8000"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

   predict:
     image: docker4data/predict_api:prod-1.0.1
     build:
       context: ./
       dockerfile: predict_api/Dockerfile
     command: /app/docker-utils/run-predict.sh
     volumes:
       - .:/app/proj/
       - static-volume:/app/htdocs/static/
     environment:
       - SITE_DIR=/app/
     networks:
       - talkvoter_net
     depends_on:
       - app
     stdin_open: true
     tty: true
     healthcheck:
       test: ["CMD", "curl", "localhost", "8000"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

   db:
     image: postgres:10-alpine
     ports:
       - "5432"
     networks:
       - talkvoter_net
     volumes:
       - pgdata:/var/lib/postgresql/data/
     healthcheck:
       test: ["CMD", "pg_isready", "-U", "postgres"]
       start_period: 5s
       interval: 30s
       timeout: 10s
       retries: 3

networks:
  talkvoter_net:

volumes:
  static-volume:
  pgdata:
