version: '3.4'
services:

   db:
     ports:
       - "9432:5432"

   app:
     ports:
       - "8000:8000"
     volumes:
       - ./.pdbrc.py:/home/sivpack/.pdbrc.py

   predict:
      ports:
        - 8888:8888
